name=MotorDriver
version=1.0
author=Tomoji Kanae
maintainer=Tomoji Kanae <gmh39599@kwansei.ac.jp>
sentence=a motor driver library
paragraph=Supports general 2pin and 3pin motor driver with PWM in Arduino UNO and ESP32
category=Device Control
architectures=*